import { Pool, neonConfig } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-serverless';
import ws from "ws";
import * as schema from "@shared/schema";

neonConfig.webSocketConstructor = ws;

if (!process.env.DATABASE_URL) {
  throw new Error(
    "DATABASE_URL must be set. Did you forget to provision a database?",
  );
}

export const pool = new Pool({ connectionString: process.env.DATABASE_URL });
export const db = drizzle({ client: pool, schema });

// Insert sample data
const sampleGames = [
  { name: "Free Fire", slug: "free-fire", description: "Battle Royale mobile game", image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400" },
  { name: "PUBG", slug: "pubg", description: "PlayerUnknown's Battlegrounds", image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400" },
  { name: "Call of Duty", slug: "cod", description: "First-person shooter game", image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400" },
  { name: "Apex Legends", slug: "apex-legends", description: "Hero-based battle royale", image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400" },
  { name: "Valorant", slug: "valorant", description: "5v5 character-based tactical shooter", image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400" },
  { name: "CS:GO", slug: "csgo", description: "Counter-Strike: Global Offensive", image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400" },
  { name: "Fortnite", slug: "fortnite", description: "Build. Battle. Create.", image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400" },
  { name: "Mobile Legends", slug: "ml", description: "Mobile MOBA game", image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400" },
];

const sampleTournaments = [
  {
    title: "Free Fire Championship",
    description: "Ultimate Battle Royale Championship with top players from across the region",
    gameId: 1,
    entryFee: "250.00",
    prizePool: "25000.00",
    maxParticipants: 50,
    currentParticipants: 32,
    mode: "squad",
    status: "live",
    startTime: new Date().toISOString(),
    rules: "No cheating, follow fair play rules, must join Discord for coordination",
    organizerId: 1,
  },
  {
    title: "PUBG Arena Masters",
    description: "Elite tournament for experienced PUBG players seeking ultimate challenge",
    gameId: 2,
    entryFee: "150.00",
    prizePool: "15000.00",
    maxParticipants: 20,
    currentParticipants: 8,
    mode: "solo",
    status: "upcoming",
    startTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    rules: "Must have minimum 100 hours playtime, rank verification required",
    organizerId: 1,
  },
  {
    title: "Call of Duty Mobile Showdown",
    description: "Fast-paced tactical shooting tournament with intense battles",
    gameId: 3,
    entryFee: "0.00",
    prizePool: "5000.00",
    maxParticipants: 32,
    currentParticipants: 18,
    mode: "duo",
    status: "upcoming",
    startTime: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    rules: "Free entry tournament, sponsored by gaming community",
    organizerId: 1,
  },
  {
    title: "Apex Legends Pro Circuit",
    description: "Professional level Apex tournament featuring the best legends and strategies",
    gameId: 4,
    entryFee: "500.00",
    prizePool: "50000.00",
    maxParticipants: 60,
    currentParticipants: 45,
    mode: "squad",
    status: "upcoming",
    startTime: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
    rules: "Premium tournament, professional setup required, streaming mandatory",
    organizerId: 1,
  },
  {
    title: "Valorant Tactical Masters",
    description: "Strategic 5v5 tournament for skilled Valorant players",
    gameId: 5,
    entryFee: "300.00",
    prizePool: "20000.00",
    maxParticipants: 40,
    currentParticipants: 22,
    mode: "squad",
    status: "upcoming",
    startTime: new Date(Date.now() + 96 * 60 * 60 * 1000).toISOString(),
    rules: "Team coordination essential, voice chat required",
    organizerId: 1,
  },
  {
    title: "CS:GO Classic Championship",
    description: "Traditional Counter-Strike tournament celebrating the classic gameplay",
    gameId: 6,
    entryFee: "200.00",
    prizePool: "18000.00",
    maxParticipants: 30,
    currentParticipants: 16,
    mode: "squad",
    status: "upcoming",
    startTime: new Date(Date.now() + 120 * 60 * 60 * 1000).toISOString(),
    rules: "Classic maps only, no modified weapons allowed",
    organizerId: 1,
  },
  {
    title: "Fortnite Build Battle Royale",
    description: "Creative building meets intense combat in this unique Fortnite tournament",
    gameId: 7,
    entryFee: "100.00",
    prizePool: "8000.00",
    maxParticipants: 100,
    currentParticipants: 67,
    mode: "solo",
    status: "live",
    startTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    rules: "Creative mode allowed, building skills heavily weighted",
    organizerId: 1,
  },
  {
    title: "Mobile Legends Bang Bang Championship",
    description: "MOBA excellence on mobile - prove your strategic dominance",
    gameId: 8,
    entryFee: "75.00",
    prizePool: "6000.00",
    maxParticipants: 40,
    currentParticipants: 33,
    mode: "squad",
    status: "live",
    startTime: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    rules: "5v5 team battles, draft mode, communication essential",
    organizerId: 1,
  },
  {
    title: "Free Fire Blitz Cup",
    description: "Quick matches, high intensity - perfect for casual competitive players",
    gameId: 1,
    entryFee: "50.00",
    prizePool: "3000.00",
    maxParticipants: 80,
    currentParticipants: 12,
    mode: "duo",
    status: "upcoming",
    startTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    rules: "Short format games, beginner friendly",
    organizerId: 1,
  },
  {
    title: "PUBG Squad Legends",
    description: "Team coordination meets survival instincts in this epic squad tournament",
    gameId: 2,
    entryFee: "400.00",
    prizePool: "35000.00",
    maxParticipants: 25,
    currentParticipants: 19,
    mode: "squad",
    status: "upcoming",
    startTime: new Date(Date.now() + 144 * 60 * 60 * 1000).toISOString(),
    rules: "Experienced teams only, must have played together for 30+ hours",
    organizerId: 1,
  },
  {
    title: "Weekend Warriors Free Tournament",
    description: "No entry fee weekend tournament for all skill levels and games",
    gameId: 1,
    entryFee: "0.00",
    prizePool: "2000.00",
    maxParticipants: 200,
    currentParticipants: 156,
    mode: "solo",
    status: "upcoming",
    startTime: new Date(Date.now() + 168 * 60 * 60 * 1000).toISOString(),
    rules: "All welcome, community sponsored prizes",
    organizerId: 1,
  },
  {
    title: "Apex Legends Beginner Bootcamp",
    description: "Learning tournament for new Apex players with coaching elements",
    gameId: 4,
    entryFee: "25.00",
    prizePool: "1500.00",
    maxParticipants: 60,
    currentParticipants: 41,
    mode: "squad",
    status: "upcoming",
    startTime: new Date(Date.now() + 192 * 60 * 60 * 1000).toISOString(),
    rules: "Beginner friendly, coaching provided, learning focused",
    organizerId: 1,
  },
  {
    title: "Monthly Legends Clash",
    description: "Cross-game monthly championship featuring multiple popular titles",
    gameId: 5,
    entryFee: "600.00",
    prizePool: "75000.00",
    maxParticipants: 35,
    currentParticipants: 8,
    mode: "squad",
    status: "upcoming",
    startTime: new Date(Date.now() + 216 * 60 * 60 * 1000).toISOString(),
    rules: "Premium monthly event, multiple game rounds, professional streaming",
    organizerId: 1,
  },
  {
    title: "Summer Gaming Festival",
    description: "Mega tournament celebrating summer with multiple games and huge prizes",
    gameId: 7,
    entryFee: "1000.00",
    prizePool: "100000.00",
    maxParticipants: 50,
    currentParticipants: 5,
    mode: "squad",
    status: "upcoming",
    startTime: new Date(Date.now() + 720 * 60 * 60 * 1000).toISOString(),
    rules: "Grand festival event, multiple rounds, celebrity guests, live audience",
    organizerId: 1,
  },
  {
    title: "Retired Champions Exhibition",
    description: "Special exhibition match featuring retired professional players",
    gameId: 6,
    entryFee: "0.00",
    prizePool: "10000.00",
    maxParticipants: 16,
    currentParticipants: 16,
    mode: "squad",
    status: "ended",
    startTime: new Date(Date.now() - 168 * 60 * 60 * 1000).toISOString(),
    rules: "Exhibition only, entertainment focused",
    organizerId: 1,
  }
];